# Generated by Django 4.1.3 on 2022-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
