# Generated by Django 4.1.3 on 2022-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='hi', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'NonBinary')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'NonBinary'), ('B', 'Both')], default='B', max_length=1),
        ),
    ]
