# Generated by Django 4.1.3 on 2022-11-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_about_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked', to='user.userprofile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocking', to='user.userprofile')),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocklist',
            field=models.ManyToManyField(related_name='blocked_by', through='user.BlockList', to='user.userprofile'),
        ),
    ]
