# Generated by Django 4.1.3 on 2022-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chatrequest_userprofile_chat_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('N', 'Unseen')], default='U', max_length=1),
        ),
    ]
