# Generated by Django 4.1.3 on 2022-11-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_chatrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=300, null=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='user.userprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_by', to='user.userprofile')),
            ],
            options={
                'unique_together': {('reporter', 'reported')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reports',
            field=models.ManyToManyField(related_name='reports_received', through='user.Reports', to='user.userprofile'),
        ),
    ]
