# Generated by Django 4.1.3 on 2022-12-02 08:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_options_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('U', 'Unseen')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=user.models.image_path),
        ),
    ]
